site_name: "PyCap"
site_description: "Evolving repo of course material for the PyCap courses"
site_url: "https://CapgeminiInventIDE.github.io/PyCap"
repo_url: "https://github.com/CapgeminiInventIDE/PyCap"
repo_name: "CapgeminiInventIDE/PyCap"

nav:
  - Getting Started: index.md
  - Courses:
    - Intro To Python:
      - Course 1: intro-to-python/course-1.md
      - Course 2: intro-to-python/course-2.md
    - Advanced Python:
      - Course 1: advanced-python/course-1.md
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Changelog: changelog.md
  - License: license.md
  - About Us: about_us.md

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/imgs/index.png
  favicon: assets/imgs/favicon.png
  palette:
    scheme: capgemini

extra_css:
  - assets/css/styles.css

extra_javascript:
  - assets/js/theme.js

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed
  - toc:
      permalink: "¤"
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list

plugins:
  - search
  - macros

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CapgeminiInventIDE
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/capgemini-invent
    - icon: fontawesome/solid/globe
      link: https://www.capgemini.com/service/invent/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/orgs/capgeminiinventide
    - icon: fontawesome/brands/discord
      link: https://discord.gg/rQcMtVE
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/capgeminiinvent/
  mentors:
    - name: Andy Challis
      github: ghandic
      description: Short bioShort bioShort bioShort bioShort bioShort bioShort bio Short bioShort bioShort bioShort bioShort bioShort bioShort bio
      courses: 
        - intro-to-python/course-1
        - intro-to-python/course-2
    - name: Tim Sanderson
      github: TimSando
      description: Short bioShort bioShort bioShort bioShort bioShort bioShort bio Short bioShort bioShort bioShort bioShort bioShort bioShort bio
      courses:
        - advanced-python/course-1